name: Build Fortran Code
on:
    push:
        paths:
            - '**/*.f90'
    workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install gfortran
      run: sudo apt-get install gfortran
    - name: Build Fortran Code
      run: gfortran -o calculator calculator.f90
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        path: calculator
        name: calculator
